### PR TITLE
Copy polish run, adding Ethereum and Bitcoin text

### PR DESCRIPTION
**Pull request by rmshea**
* Changed homepage copy

* Added ETH / BTC comparison text lines on end game

* Added button to house a leaderboard

### CODE REVIEW

**Comment by rmshea** [comment]
@jstarry, is there an easy way to get to the `results` end screen without starting up the server infrastructure?

**Comment by jstarry** [comment]
@rmshea is there anything holding this up?

**Comment by rmshea** [comment]
@jstarry nope!

**Comment by jstarry** [comment]
@mergifyio rebase

**Comment by jstarry** [comment]
@Mergifyio rebase

**Comment by jstarry** [comment]
@Mergifyio rebase

**Pull request merged**
